project:
  type: website
  output-dir: docs

website:
  title: "Sally Tsai"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: courses.qmd
        text: Courses
      - text: Projects
        menu:
          - text: Brazil Health Outcomes (Quant)
            href: pdfs/brazil-health-outcome.pdf
          - text: "Growth Decomposition: Azerbaijan vs Turkey (Quant/memo)"
            href: pdfs/Asian Development Bank Internal Memorandum.pdf
          - text: Taiwan Nuclear Policy Cycle (Memo)
            href: pdfs/PPG401 policy cycle.pdf
          - text: "Taiwan's Energy Transition (Quant/memo)"
            href: pdfs/POl474 Paper 1.pdf
          - text: Democracy, Equality, and State Violence (Quant)
            href: pdfs/Democracy, Equality, and State Violence.pdf
          - text: "Israel Constitutional Void (Political Science)"
            href: pdfs/POL377 Essay.pdf

    
      - text: "Resume"
        href: pdfs/Sally Resume.pdf
      - icon: github
        href: https://github.com/sallyytsai
      - icon: envelope
        href: "mailto:sallytsai6640@gmail.com"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: true

